k0s_version: "v1.34.3+k0s.0"
k0s_image: "docker.io/k0sproject/k0s:v1.34.3+k0s.0"
k0s_install_dir: "/usr/local/bin"
k0s_config_path: "/etc/k0s/k0s.yaml"

k0s_arch_map:
  x86_64: amd64
  amd64: amd64
  aarch64: arm64
  arm64: arm64
